# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-17 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
