# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-17 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_remove_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, choices=[('HEALTH', 'HEALTH'), ('AGRICULTURE', 'AGRICULTURE'), ('UNEMPLOYMENT', 'UNEMPLOYMENT'), ('CORRUPTION', 'CORRUPTION'), ('EDUCATION', 'EDUCATION')], max_length=20, null=True),
        ),
    ]
