# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-17 07:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20180317_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_name',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
