# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-17 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20180317_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user_name',
        ),
    ]
