# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-17 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_remove_question_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
