# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-17 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_question_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('user_name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='post_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ask', models.CharField(max_length=20000)),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='ans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.post_question'),
        ),
    ]
