# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-17 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_auto_20180317_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_question',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
