# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-17 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_auto_20180317_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_question',
            name='likes',
        ),
    ]
