# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-17 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_remove_post_question_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='ans',
            new_name='ques',
        ),
    ]
